name: ql_gen
description: A library for generating dart code from GraphQL schema.
version: 0.1.3
repository: https://github.com/roadroot/ql_gen

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  args: ^2.4.0
  tokenizer_parser: ^0.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
